<?php


namespace Exolnet\Bento\Tests\Unit\Strategy;

use Exolnet\Bento\Bento;
use Exolnet\Bento\Feature;
use Exolnet\Bento\Strategy\LogicAnd;
use Exolnet\Bento\Tests\UnitTest;
use Mockery;

class StrategyContainerTest extends UnitTest
{

    protected $bento;
    protected $feature;
    protected $logic;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->bento = Mockery::mock(Bento::class);
        $this->feature = Mockery::mock(Feature::class);

    }

    /**
     * @return void
     * @test
     */
    public function testGetFeature(): void
    {
        $this->logic = new LogicAnd($this->bento, $this->feature);
        self::assertEquals($this->feature, $this->logic->getFeature());
    }


}
