<?php

namespace Exolnet\Bento\Tests\Unit\Strategy;

use Exolnet\Bento\Bento;
use Exolnet\Bento\Feature;
use Exolnet\Bento\Strategy\VisitorPercent;
use Exolnet\Bento\Tests\UnitTest;

class VisitorPercentTest extends UnitTest
{
    protected $bento;
    protected $feature;
    protected $visitorPercent;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->bento = \Mockery::mock(Bento::class);
        $this->feature = \Mockery::mock(Feature::class);
        $this->visitorPercent = new VisitorPercent($this->bento, $this->feature, 50);
    }

    /**
     * @return void
     * @test
     */
    public function testGetFeature(): void
    {
        $this->bento->shouldReceive('getVisitorId')->once()->andReturn(1234);

        self::assertEquals(1234, $this->visitorPercent->getUniqueId());
    }
}
